### ISSUE TITLE
Can't logAction at the start of an activity

### ISSUE THREAD

**Issue by esnaultdev** [rakuten-ads/Rakuten-Reward-Native-Android#1]
## Context
In my `Application` class, I initialize the SDK with `RakutenReward.init(appContext, appCode)`.

I have multiple activities in my app, but only one that is related to the Rakuten Reward.
Because of this, it's the only activity that is bound to the Rakuten SDK, using `RakutenRewardManager.bindRakutenRewardIn(lifecycleOwner, activity)`.

## Current Behavior

With the user already logged in, trying to call `RakutenReward.logAction(actionCode, { }, { })` in the activity `onCreate`, `onStart` or `onResume` results in `RakutenRewardAPIError.SDKNOTACTIVE `.

Note that:
- `RakutenAuth.hasUserSignedIn()` returns `true` (we have a valid `token`).
- `RakutenReward.status` returns `RakutenRewardSDKStatus.OFFLINE`.

## Expected Behavior

`RakutenReward.logAction` should not fail if we have a signed in user.

## Potential fix

I think that this is due to the member info being retrieved too late, since I also see this log afterwards:
> RakutenRewardSDK: Reward SDK is not active
> RakutenRewardSDK: MemberInfo Success

In my opinion, there are two possible solutions (or maybe a combination of both):
- Retrieve `MemberInfo` early, after the SDK is first initialized, and not when the first bound activity starts
- While retrieving `MemberInfo`, queue `logAction` to a list of pending actions

## Steps to Reproduce

1. Launch the app and login with a user using `RakutenAuth.openLoginPage(activity, requestCode)`.
2. Close the app completely.
3. Launch the app again.
4. Launch an activity that is bound to the RakutenSDK and call `logAction` in `onStart`.

## Details
Artifact version: `com.rakuten.android:rewardsdknative-core:2.0.0`
Android SDK 29

**Comment by esnaultdev** [comment]
By the way, let me know if the Github issue tracker is not the right place to report this kind of issue.
I would be happy to follow-up on the right bugtracker.

**Comment by daiji-ito-rakuten** [comment]
Android Lifecycle (onStart, onResume) event and SDK activation event cycle does not match.

SDK activation needs to check backend API data.  (= Async data request is invoked)

So, we prepared RakutenRewardListener to get callback from sdk.

 

In this case, your should use fun onSDKStatusChanged(status : RakutenRewardSDKStatus) to detect SDK activation

For more details, please take a look https://github.com/rakuten-ads/Rakuten-Reward-Native-Android/blob/master/doc/APIReference/README.md#rakutenrewardlistener
